export default { promptops: {
  brand:{subtitle:'Enterprise Prompt Management & Evaluation'}, common:{comingSoon:'Coming Soon',comingSoonDescription:'This module is planned for a later delivery phase.',loading:'Loading…',loadError:'Unable to load data.',initError:'Unable to initialize PromptOps Studio',retry:'Retry',cancel:'Cancel',create:'Create',phase2:'Available in Phase 2'},
  nav:{overview:'Overview',promptManagement:'Prompt Management',governance:'Governance',system:'System',dashboard:'Dashboard',prompts:'Prompt Library',playground:'Playground',invocations:'Invocation History',datasets:'Datasets',evaluations:'Evaluations',experiments:'Experiments',approvals:'Approval Center',models:'Models',analytics:'Usage Analytics',settings:'Settings',legacy:'Legacy Optimizer'},roles:{aiProductManager:'AI Product Manager'},
  status:{draft:'Draft',testing:'Testing',pending_approval:'Pending Approval',published:'Published',archived:'Archived'},risk:{low:'Low',medium:'Medium',high:'High'},
  dashboard:{title:'Dashboard',description:'Prompt portfolio health and governance overview',viewLibrary:'View Prompt Library',total:'Total Prompts',published:'Published',drafts:'Drafts',pending:'Pending Approval',averageScore:'Average Evaluation Score',highRisk:'High Risk Prompts',statusDistribution:'Prompt Status Distribution',recentPrompts:'Recently Updated Prompts',noHighRisk:'No high-risk prompts',recentActivity:'Recent Activity',activityHint:'Activity shown here is derived from prompt update timestamps.',wasUpdated:'was updated'},
  library:{title:'Prompt Library',description:'Manage reusable prompt assets across the workspace',assets:'assets',newPrompt:'New Prompt',descriptionField:'Description',emptyTitle:'No prompts found',emptyDescription:'Adjust or clear the filters to see more results.',archiveConfirm:'Archive “{name}”? The asset will remain available in history.'},
  filters:{search:'Search name, description or scenario',allStatuses:'All statuses',allCategories:'All categories',allDepartments:'All departments',allRisks:'All risk levels',clear:'Clear filters'},
  table:{name:'Name',scenario:'Business Scenario',category:'Category',department:'Department',owner:'Owner',version:'Version',model:'Model',status:'Status',risk:'Risk',score:'Evaluation Score',updatedAt:'Updated',actions:'Actions'},actions:{view:'View',edit:'Edit',duplicate:'Duplicate',archive:'Archive',copy:'Copy'},
  detail:{title:'Prompt Detail',back:'Back to Prompt Library',backDashboard:'Back to Dashboard',notFound:'Prompt not found.',openPlayground:'Open in Playground',variables:'Variables',required:'Required',optional:'Optional',modelConfig:'Model Configuration'},
  editor:{createPrompt:'Create Prompt',editPrompt:'Edit Prompt',saveDraft:'Save Draft',saveChanges:'Save Changes',saveNewVersion:'Save as New Version',versionType:'Version Type',majorVersion:'Major Version',minorVersion:'Minor Version',changeSummary:'Change Summary',changeReason:'Change Reason',basicInformation:'Basic Information',promptContent:'Prompt Content',variables:'Variables',addVariable:'Add Variable',noVariables:'Variables in {{double braces}} are detected automatically.',variableDiagnostics:'Variable Diagnostics',invalidVariable:'Invalid variable name',unusedVariable:'Unused Variable',removeVariable:'Remove Variable',modelConfig:'Model Configuration',outputConfig:'Output Configuration',outputType:'Output Type',expectedOutput:'Expected Output Format',unsavedChanges:'Unsaved Changes',promptNotFound:'Prompt not found',archivedCannotEdit:'Archived prompts cannot be edited.',restorePrompt:'Restore Prompt'},
  version:{history:'Version History',detail:'Version Detail',currentVersion:'Current Version',versions:'versions',restore:'Restore as New Version',empty:'No versions found.',notFound:'Version not found.',backDetail:'Back to Prompt Detail'},
  playground:{title:'Use the existing optimization workspace',description:'The proven Prompt Optimizer workspace remains available while the dedicated PromptOps playground is built.',openLegacy:'Open Legacy Optimizer',capability1:'System and user prompt optimization',capability2:'Multi-model testing and comparison',capability3:'Variable and multi-turn workspaces'},settings:{about:'About',openSource:'Built on the open-source Prompt Optimizer project. Licensed under AGPL-3.0.'}
}} as const
