<template>
  <section class="page">
    <div class="heading"><div><h2>{{ t('promptops.library.title') }}</h2><p>{{ t('promptops.library.description') }} · {{ total }} {{ t('promptops.library.assets') }}</p></div><button class="primary" @click="router.push('/prompts/new')">+ {{ t('promptops.library.newPrompt') }}</button></div>
    <div class="filters">
      <input v-model="filters.search" data-testid="prompt-search" :placeholder="t('promptops.filters.search')" @input="load"/>
      <select v-model="filters.status" @change="load"><option value="">{{ t('promptops.filters.allStatuses') }}</option><option v-for="value in PROMPT_STATUSES" :key="value" :value="value">{{ t(`promptops.status.${value}`) }}</option></select>
      <select v-model="filters.category" @change="load"><option value="">{{ t('promptops.filters.allCategories') }}</option><option v-for="value in facets.categories" :key="value">{{ value }}</option></select>
      <select v-model="filters.department" @change="load"><option value="">{{ t('promptops.filters.allDepartments') }}</option><option v-for="value in facets.departments" :key="value">{{ value }}</option></select>
      <select v-model="filters.riskLevel" @change="load"><option value="">{{ t('promptops.filters.allRisks') }}</option><option v-for="value in risks" :key="value" :value="value">{{ t(`promptops.risk.${value}`) }}</option></select>
      <select v-model="filters.sortBy" @change="load"><option value="updatedAt">{{ t('promptops.table.updatedAt') }}</option><option value="name">{{ t('promptops.table.name') }}</option><option value="lastEvaluationScore">{{ t('promptops.table.score') }}</option></select>
      <button class="secondary" @click="toggleDirection">{{ filters.sortDirection === 'asc' ? '↑' : '↓' }}</button>
    </div>
    <div v-if="loading" class="state">{{ t('promptops.common.loading') }}</div><div v-else-if="error" class="error">{{ t('promptops.common.loadError') }}<button @click="load">{{ t('promptops.common.retry') }}</button></div>
    <div v-else-if="!prompts.length" class="state" data-testid="empty-state"><strong>{{ t('promptops.library.emptyTitle') }}</strong><p>{{ t('promptops.library.emptyDescription') }}</p><button class="secondary" @click="clearFilters">{{ t('promptops.filters.clear') }}</button></div>
    <div v-else class="table-wrap"><table><thead><tr><th>{{ t('promptops.table.name') }}</th><th>{{ t('promptops.table.scenario') }}</th><th>{{ t('promptops.table.department') }}</th><th>{{ t('promptops.table.owner') }}</th><th>{{ t('promptops.table.version') }}</th><th>{{ t('promptops.table.model') }}</th><th>{{ t('promptops.table.status') }}</th><th>{{ t('promptops.table.risk') }}</th><th>{{ t('promptops.table.score') }}</th><th>{{ t('promptops.table.updatedAt') }}</th><th>{{ t('promptops.table.actions') }}</th></tr></thead><tbody><tr v-for="prompt in prompts" :key="prompt.id" data-testid="prompt-row"><td><RouterLink :to="`/prompts/${prompt.id}`"><strong>{{ prompt.name }}</strong></RouterLink><small>{{ prompt.category }}</small></td><td>{{ prompt.businessScenario }}</td><td>{{ prompt.department }}</td><td>{{ prompt.owner.name }}</td><td>{{ prompt.currentVersion }}</td><td>{{ prompt.modelName }}</td><td><span class="tag">{{ t(`promptops.status.${prompt.status}`) }}</span></td><td><span class="tag" :class="prompt.riskLevel">{{ t(`promptops.risk.${prompt.riskLevel}`) }}</span></td><td>{{ prompt.lastEvaluationScore ?? '—' }}</td><td>{{ formatDate(prompt.updatedAt) }}</td><td><div class="row-actions"><RouterLink :to="`/prompts/${prompt.id}`">{{ t('promptops.actions.view') }}</RouterLink><RouterLink v-if="prompt.status!=='archived'" :to="`/prompts/${prompt.id}/edit`">{{ t('promptops.actions.edit') }}</RouterLink><button @click="duplicate(prompt)">{{ t('promptops.actions.duplicate') }}</button><button data-testid="archive-action" :disabled="prompt.status === 'archived'" @click="requestArchive(prompt)">{{ t('promptops.actions.archive') }}</button></div></td></tr></tbody></table></div>
    <div v-if="archiveTarget" class="overlay" @click.self="archiveTarget=undefined"><div class="modal"><h3>{{ t('promptops.actions.archive') }}</h3><p>{{ t('promptops.library.archiveConfirm', { name: archiveTarget.name }) }}</p><div class="modal-actions"><button @click="archiveTarget=undefined">{{ t('promptops.common.cancel') }}</button><button class="danger" data-testid="confirm-archive" @click="archivePrompt">{{ t('promptops.actions.archive') }}</button></div></div></div>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { PROMPT_STATUSES, type PromptOpsPrompt as Prompt, type PromptListQuery, type PromptRiskLevel } from '@prompt-optimizer/core'
import { usePromptOpsServices } from '../../services/promptops'; import { usePromptOpsUiStore } from '../../stores/promptops/usePromptOpsUiStore'
const { t } = useI18n(); const router=useRouter(); const services = usePromptOpsServices(); const store = usePromptOpsUiStore(); const risks: PromptRiskLevel[] = ['low','medium','high']
const filters = reactive({ search: '', status: '', category: '', department: '', riskLevel: '', sortBy: 'updatedAt', sortDirection: 'desc', ...store.promptFilters })
watch(filters, value => { store.promptFilters = { ...value } as Omit<PromptListQuery,'workspaceId'> }, { deep: true })
const prompts = ref<Prompt[]>([]); const allPrompts = ref<Prompt[]>([]); const loading = ref(true); const error = ref(''); const archiveTarget = ref<Prompt>()
const total = computed(() => allPrompts.value.length); const facets = computed(() => ({ categories:[...new Set(allPrompts.value.map(p=>p.category))].sort(), departments:[...new Set(allPrompts.value.map(p=>p.department))].sort() }))
const query = (): PromptListQuery => ({ workspaceId:store.currentWorkspaceId, search:filters.search||undefined, status:filters.status as PromptListQuery['status']||undefined, category:filters.category||undefined, department:filters.department||undefined, riskLevel:filters.riskLevel as PromptRiskLevel||undefined, sortBy:filters.sortBy as PromptListQuery['sortBy'], sortDirection:filters.sortDirection as PromptListQuery['sortDirection'] })
const load = async () => { loading.value=true; error.value=''; try { [prompts.value,allPrompts.value]=await Promise.all([services.promptRepository.list(query()),services.promptRepository.list({workspaceId:store.currentWorkspaceId})]) } catch(cause){error.value=cause instanceof Error?cause.message:String(cause)} finally{loading.value=false} }
onMounted(load); const clearFilters=()=>{Object.assign(filters,{search:'',status:'',category:'',department:'',riskLevel:'',sortBy:'updatedAt',sortDirection:'desc'});load()}; const toggleDirection=()=>{filters.sortDirection=filters.sortDirection==='asc'?'desc':'asc';load()}
const duplicate=async(prompt:Prompt)=>{await services.promptEditorService.duplicate(prompt.id,`${prompt.name} (${t('promptops.actions.copy')})`);await load()}
const requestArchive=(prompt:Prompt)=>{archiveTarget.value=prompt};const archivePrompt=async()=>{if(!archiveTarget.value)return;await services.promptRepository.archive(archiveTarget.value.id);archiveTarget.value=undefined;await load()};const formatDate=(value:string)=>new Intl.DateTimeFormat(typeof document==='undefined'?'en':document.documentElement.lang||'en',{dateStyle:'medium'}).format(new Date(value))
</script>
<style scoped>
.page{display:grid;gap:20px}.heading{display:flex;justify-content:space-between}.heading h2{margin:0;font-size:25px}.heading p{color:#64748b}.primary,.secondary,.danger,button{border:1px solid #d1d5db;border-radius:7px;padding:8px 12px;cursor:pointer;background:white}.primary{background:#2563eb;color:white;border-color:#2563eb}.danger{background:#dc2626;color:white}.filters{display:grid;grid-template-columns:minmax(220px,2fr) repeat(5,minmax(120px,1fr)) 42px;gap:8px}.filters input,.filters select,.modal input,.modal textarea{border:1px solid #d1d5db;border-radius:7px;padding:9px;background:var(--n-color,#fff);color:inherit}.table-wrap{overflow:auto;background:var(--n-color,#fff);border:1px solid #e5e7eb;border-radius:10px}table{width:100%;min-width:1250px;border-collapse:collapse;text-align:left}th,td{padding:12px 10px;border-bottom:1px solid #e5e7eb;font-size:12px;vertical-align:top}th{color:#64748b}td:first-child{display:flex;flex-direction:column;gap:4px}td a{color:#1d4ed8;text-decoration:none}td small{color:#64748b}.tag{white-space:nowrap;padding:3px 7px;border-radius:12px;background:#eef2ff}.tag.high{background:#fee2e2;color:#991b1b}.tag.medium{background:#fef3c7;color:#92400e}.row-actions{display:flex;gap:8px}.row-actions button{padding:0;border:0;background:none;color:#1d4ed8}.row-actions button:disabled{color:#94a3b8}.state,.error{text-align:center;padding:55px;background:white;border:1px solid #e5e7eb;border-radius:10px}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:50}.modal{width:min(520px,calc(100vw - 40px));padding:22px;background:var(--n-color,#fff);border-radius:10px;display:grid;gap:14px}.modal h3{margin:0}.modal label{display:grid;gap:6px;font-size:12px}.modal textarea{min-height:75px}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:1100px){.filters{grid-template-columns:repeat(3,1fr)}}
</style>
