export default { promptops: {
  brand:{subtitle:'企业 Prompt 管理与评测平台'},common:{comingSoon:'即将推出',comingSoonDescription:'此模块将在后续开发阶段交付。',loading:'加载中…',loadError:'数据加载失败。',initError:'PromptOps Studio 初始化失败',retry:'重试',cancel:'取消',create:'创建',phase2:'Phase 2 提供'},
  nav:{overview:'概览',promptManagement:'Prompt 管理',governance:'治理',system:'系统',dashboard:'仪表盘',prompts:'Prompt 资产库',playground:'调试台',invocations:'调用历史',datasets:'测试数据集',evaluations:'评测',experiments:'实验',approvals:'审批中心',models:'模型管理',analytics:'使用分析',settings:'设置',legacy:'旧版优化器'},roles:{aiProductManager:'AI 产品经理'},
  status:{draft:'草稿',testing:'测试中',pending_approval:'待审批',published:'已发布',archived:'已归档'},risk:{low:'低',medium:'中',high:'高'},
  dashboard:{title:'仪表盘',description:'Prompt 资产健康度与治理概览',viewLibrary:'查看 Prompt 资产库',total:'Prompt 总数',published:'已发布',drafts:'草稿',pending:'待审批',averageScore:'平均评测分数',highRisk:'高风险 Prompt',statusDistribution:'Prompt 状态分布',recentPrompts:'最近更新的 Prompt',noHighRisk:'暂无高风险 Prompt',recentActivity:'最近活动',activityHint:'此处活动由 Prompt 更新时间推导生成。',wasUpdated:'已更新'},
  library:{title:'Prompt 资产库',description:'统一管理工作空间中的可复用 Prompt 资产',assets:'项资产',newPrompt:'新建 Prompt',descriptionField:'描述',emptyTitle:'未找到 Prompt',emptyDescription:'请调整或清除筛选条件。',archiveConfirm:'确认归档“{name}”？该资产仍会保留在历史数据中。'},
  filters:{search:'搜索名称、描述或业务场景',allStatuses:'全部状态',allCategories:'全部分类',allDepartments:'全部部门',allRisks:'全部风险等级',clear:'清除筛选'},
  table:{name:'名称',scenario:'业务场景',category:'分类',department:'部门',owner:'负责人',version:'版本',model:'模型',status:'状态',risk:'风险',score:'评测分数',updatedAt:'更新时间',actions:'操作'},actions:{view:'查看',edit:'编辑',duplicate:'复制',archive:'归档',copy:'副本'},
  detail:{title:'Prompt 详情',back:'返回 Prompt 资产库',backDashboard:'返回仪表盘',notFound:'未找到 Prompt。',openPlayground:'在调试台中打开',variables:'变量',required:'必填',optional:'选填',modelConfig:'模型配置'},
  editor:{createPrompt:'创建 Prompt',editPrompt:'编辑 Prompt',saveDraft:'保存草稿',saveChanges:'保存修改',saveNewVersion:'保存为新版本',versionType:'版本类型',majorVersion:'主版本',minorVersion:'次版本',changeSummary:'变更摘要',changeReason:'变更原因',basicInformation:'基础信息',promptContent:'Prompt 内容',variables:'变量',addVariable:'添加变量',noVariables:'使用双花括号定义的变量会被自动识别。',variableDiagnostics:'变量诊断',invalidVariable:'变量名称无效',unusedVariable:'未使用变量',removeVariable:'移除变量',modelConfig:'模型配置',outputConfig:'输出配置',outputType:'输出类型',expectedOutput:'预期输出格式',unsavedChanges:'有未保存的修改',promptNotFound:'未找到 Prompt',archivedCannotEdit:'已归档的 Prompt 不能编辑。',restorePrompt:'恢复 Prompt'},
  version:{history:'版本历史',detail:'版本详情',currentVersion:'当前版本',versions:'个版本',restore:'恢复为新版本',empty:'暂无版本。',notFound:'未找到版本。',backDetail:'返回 Prompt 详情'},
  playground:{title:'使用现有 Prompt 优化工作区',description:'在专用 PromptOps 调试台开发完成前，继续保留并复用成熟的 Prompt Optimizer 工作区。',openLegacy:'打开旧版优化器',capability1:'System 与 User Prompt 优化',capability2:'多模型测试与对比',capability3:'变量与多轮对话工作区'},settings:{about:'关于',openSource:'基于开源 Prompt Optimizer 项目构建，使用 AGPL-3.0 许可证。'}
}} as const
