
export default { promptops: {
  brand:{subtitle:'企业 Prompt 管理与评测平台'},common:{comingSoon:'即将推出',comingSoonDescription:'此模块将在后续开发阶段交付。',loading:'加载中…',loadError:'数据加载失败。',initError:'PromptOps Studio 初始化失败',retry:'重试',cancel:'取消',create:'创建',phase2:'Phase 2 提供'},
  nav:{overview:'概览',promptManagement:'Prompt 管理',governance:'治理',system:'系统',dashboard:'仪表盘',prompts:'Prompt 资产库',playground:'调试台',invocations:'调用历史',datasets:'测试数据集',evaluations:'评测',experiments:'实验',approvals:'审批中心',models:'模型管理',analytics:'使用分析',settings:'设置',legacy:'旧版优化器'},roles:{aiProductManager:'AI 产品经理'},
  status:{draft:'草稿',testing:'测试中',pending_approval:'待审批',published:'已发布',archived:'已归档'},risk:{low:'低',medium:'中',high:'高'},
  dashboard:{title:'仪表盘',description:'Prompt 资产健康度与治理概览',viewLibrary:'查看 Prompt 资产库',total:'Prompt 总数',published:'已发布',drafts:'草稿',pending:'待审批',averageScore:'平均评测分数',highRisk:'高风险 Prompt',statusDistribution:'Prompt 状态分布',recentPrompts:'最近更新的 Prompt',noHighRisk:'暂无高风险 Prompt',recentActivity:'最近活动',activityHint:'此处活动由 Prompt 更新时间推导生成。',wasUpdated:'已更新'},
  library:{title:'Prompt 资产库',description:'统一管理工作空间中的可复用 Prompt 资产',assets:'项资产',newPrompt:'新建 Prompt',descriptionField:'描述',emptyTitle:'未找到 Prompt',emptyDescription:'请调整或清除筛选条件。',archiveConfirm:'确认归档“{name}”？该资产仍会保留在历史数据中。'},
  filters:{search:'搜索名称、描述或业务场景',allStatuses:'全部状态',allCategories:'全部分类',allDepartments:'全部部门',allRisks:'全部风险等级',clear:'清除筛选'},
  table:{name:'名称',scenario:'业务场景',category:'分类',department:'部门',owner:'负责人',version:'版本',model:'模型',status:'状态',risk:'风险',score:'评测分数',updatedAt:'更新时间',actions:'操作'},actions:{view:'查看',edit:'编辑',duplicate:'复制',archive:'归档',copy:'副本'},
  detail:{title:'Prompt 详情',back:'返回 Prompt 资产库',backDashboard:'返回仪表盘',notFound:'未找到 Prompt。',openPlayground:'在调试台中打开',variables:'变量',required:'必填',optional:'选填',modelConfig:'模型配置'},
  editor:{createPrompt:'创建 Prompt',editPrompt:'编辑 Prompt',saveDraft:'保存草稿',saveChanges:'保存修改',saveNewVersion:'保存为新版本',versionType:'版本类型',majorVersion:'主版本',minorVersion:'次版本',changeSummary:'变更摘要',changeReason:'变更原因',basicInformation:'基础信息',promptContent:'Prompt 内容',variables:'变量',addVariable:'添加变量',noVariables:'使用双花括号定义的变量会被自动识别。',variableDiagnostics:'变量诊断',invalidVariable:'变量名称无效',unusedVariable:'未使用变量',removeVariable:'移除变量',modelConfig:'模型配置',outputConfig:'输出配置',outputType:'输出类型',expectedOutput:'预期输出格式',unsavedChanges:'有未保存的修改',promptNotFound:'未找到 Prompt',archivedCannotEdit:'已归档的 Prompt 不能编辑。',restorePrompt:'恢复 Prompt'},
  version:{history:'版本历史',detail:'版本详情',currentVersion:'当前版本',versions:'个版本',restore:'恢复为新版本',empty:'暂无版本。',notFound:'未找到版本。',backDetail:'返回 Prompt 详情'},
  playground:{title:'使用现有 Prompt 优化工作区',description:'在专用 PromptOps 调试台开发完成前，继续保留并复用成熟的 Prompt Optimizer 工作区。',openLegacy:'打开旧版优化器',capability1:'System 与 User Prompt 优化',capability2:'多模型测试与对比',capability3:'变量与多轮对话工作区'},
  datasets:{title:'数据集资产库',description:'管理可复用的回归测试数据。',create:'创建数据集',edit:'编辑数据集',detail:'数据集详情',name:'数据集名称',descriptionField:'描述',active:'启用',archived:'已归档',allStatuses:'全部状态',testCases:'测试用例',addCase:'新增测试用例',editCase:'编辑测试用例',duplicateCase:'复制测试用例',deleteCase:'删除测试用例',batchDelete:'批量删除',selected:'已选择 {count} 项',variables:'变量（JSON）',expectedOutput:'预期输出',validationRules:'校验规则',requiredKeywords:'必含关键词',forbiddenKeywords:'禁用关键词',exactMatch:'精确匹配',outputType:'输出类型',jsonFields:'JSON 字段',jsonSchema:'JSON Schema',tags:'标签',importDataset:'导入数据集',exportDataset:'导出数据集',selectFile:'选择 JSON 文件',importPreview:'导入预览',validCases:'有效用例',errors:'错误',warnings:'警告',caseIndex:'用例序号',jsonPath:'JSON 路径',confirmImport:'确认导入',importSuccess:'数据集导入成功。',importFailed:'导入失败。',exportSuccess:'数据集已导出。',empty:'暂无数据集。',noCases:'暂无测试用例。',noResults:'没有符合筛选条件的结果。',notFound:'未找到数据集。',archivedReadonly:'已归档数据集为只读状态。',restore:'恢复数据集',archive:'归档数据集',archiveConfirm:'确认归档此数据集？',deleteConfirm:'确认删除此测试用例？',batchDeleteConfirm:'确认删除选中的测试用例？',fileTooLarge:'所选文件过大。',invalidJson:'JSON 无效。',atomic:'导入采用原子策略：任何错误都会阻止全部写入。',runEvaluation:'运行评测',comingSoon:'即将推出',save:'保存',close:'关闭',back:'返回数据集',search:'搜索数据集',caseSearch:'搜索测试用例',sort:'排序',status:'状态',count:'共 {count} 个数据集',totalCases:'共 {count} 个测试用例',created:'创建时间',updated:'更新时间',actions:'操作',duplicate:'复制',clearFilters:'清除筛选',view:'查看',metadata:'编辑信息'},evaluations:{configuration:'评估配置',dataset:'数据集',selectPrompt:'选择提示词',selectVersion:'选择版本',selectModel:'选择模型',noEnabledModels:'没有已启用模型',testCaseSelection:'测试用例选择',allCases:'全部用例',selectedCases:'已选用例',filterByTag:'按标签筛选',temperature:'温度',maxTokens:'最大 Token',concurrency:'并发数',summary:'配置摘要',pricingUnavailable:'价格不可用',start:'开始评估',running:'运行中',history:'评估历史',historyDescription:'查看并重试批量评估运行。',search:'搜索运行',allStatuses:'全部状态',empty:'暂无评估运行。',run:'评估运行',prompt:'提示词',model:'模型',progress:'进度',invocationSuccessRate:'调用成功率',validationPassRate:'校验通过率',retryEntire:'重试全部',retryFailed:'重试失败项',retryCase:'重试此用例',delete:'删除',deleteConfirm:'删除此评估运行及其结果？',notFound:'未找到评估。',configurationSnapshot:'配置快照',cancel:'取消评估',cancelConfirm:'取消待执行用例？部分运行中请求可能无法中断。',metrics:'指标',averageLatency:'平均延迟',totalTokens:'总 Token',totalCost:'总成本',averageScore:'平均分',case:'测试用例',statusLabel:'状态',deterministicValidation:'确定性校验',latency:'延迟',tokens:'Token',output:'输出',openInvocation:'打开调用详情',status:{queued:'排队中',running:'运行中',completed:'已完成',completed_with_errors:'完成但有错误',failed:'失败',cancelled:'已取消',pending:'待执行',succeeded:'调用成功',skipped:'已跳过'}},settings:{about:'关于',openSource:'基于开源 Prompt Optimizer 项目构建，使用 AGPL-3.0 许可证。'}
}} as const
