import{computed,onBeforeUnmount,reactive,ref,watch}from'vue'
import{onBeforeRouteLeave,useRoute,useRouter}from'vue-router'
import{useI18n}from'vue-i18n'
import{DEFAULT_USER,DEFAULT_WORKSPACE_ID,PROMPT_DEFAULTS,parsePromptVariables,syncPromptVariables,validatePrompt,type PromptOpsPrompt as Prompt,type PromptOpsValidationIssue as PromptValidationIssue}from'@prompt-optimizer/core'
import{usePromptOpsServices}from'../../services/promptops'
const blank=():Prompt=>{const now=new Date().toISOString();return{id:'',workspaceId:DEFAULT_WORKSPACE_ID,name:'',description:'',businessScenario:'',category:'',department:'',owner:DEFAULT_USER,systemPrompt:'',userPrompt:'',variables:[],expectedOutputFormat:'',outputType:PROMPT_DEFAULTS.outputType,modelProvider:PROMPT_DEFAULTS.modelProvider,modelName:PROMPT_DEFAULTS.modelName,temperature:PROMPT_DEFAULTS.temperature,maxTokens:PROMPT_DEFAULTS.maxTokens,status:PROMPT_DEFAULTS.status,riskLevel:PROMPT_DEFAULTS.riskLevel,currentVersion:PROMPT_DEFAULTS.currentVersion,createdAt:now,updatedAt:now}}
const normalize=(p:Prompt)=>JSON.stringify({...p,variables:p.variables.map(v=>({...v,options:v.options?[...v.options]:undefined}))})
export function usePromptEditor(){const route=useRoute(),router=useRouter(),services=usePromptOpsServices(),{t}=useI18n();const form=reactive<Prompt>(blank()),initial=ref(''),loading=ref(true),saving=ref(false),error=ref(''),issues=ref<PromptValidationIssue[]>([]),diagnostics=ref<ReturnType<typeof parsePromptVariables>['diagnostics']>([]);const editMode=computed(()=>Boolean(route.params.id));const dirty=computed(()=>!loading.value&&normalize(form)!==initial.value);let allowLeave=false
 const sync=()=>{const parsed=parsePromptVariables(form.systemPrompt,form.userPrompt);diagnostics.value=parsed.diagnostics;form.variables=syncPromptVariables(form.variables,parsed)}
 watch(()=>[form.systemPrompt,form.userPrompt],sync)
 const load=async()=>{loading.value=true;error.value='';try{Object.assign(form,blank());if(editMode.value){const value=await services.promptRepository.getById(String(route.params.id));if(!value)error.value='notFound';else Object.assign(form,value)}sync();initial.value=normalize(form)}catch(cause){error.value=cause instanceof Error?cause.message:String(cause)}finally{loading.value=false}}
 watch(()=>String(route.params.id??''),async(current,previous)=>{if(current!==previous){allowLeave=false;await load()}})
 const validate=()=>{const result=validatePrompt(form);issues.value=result.issues;if(!result.valid)window.alert(`${result.issues[0]?.field}: ${result.issues[0]?.message}`);return result.valid};const markSaved=()=>{initial.value=normalize(form)}
 const saveDraft=async()=>{if(!validate())return;saving.value=true;try{const{id:_id,createdAt:_c,updatedAt:_u,currentVersion:_v,...input}=form;const saved=await services.promptEditorService.create(input);Object.assign(form,saved);markSaved();allowLeave=true;await router.replace(`/prompts/${saved.id}`)}catch(cause){console.error('[PromptEditor] Create failed',cause);window.alert(cause instanceof Error?cause.message:String(cause))}finally{saving.value=false}}
 const navigateToLibrary=async()=>{allowLeave=true;await router.replace({name:'promptops-prompts'})}
 const saveChanges=async()=>{if(!validate())return;saving.value=true;try{Object.assign(form,await services.promptEditorService.saveChanges({...form}));markSaved();await navigateToLibrary()}catch(cause){console.error('[PromptEditor] Save failed',cause);window.alert(cause instanceof Error?cause.message:String(cause))}finally{saving.value=false}}
 const saveVersion=async(summary:string,reason:string,increment:'minor'|'major'):Promise<boolean>=>{if(!validate())return false;saving.value=true;try{const version=await services.promptEditorService.saveNewVersion({...form},{changeSummary:summary,changeReason:reason,increment});form.currentVersion=version.versionNumber;form.updatedAt=version.createdAt;markSaved();await navigateToLibrary();return true}catch(cause){console.error('[PromptEditor] Version save failed',cause);window.alert(cause instanceof Error?cause.message:String(cause));return false}finally{saving.value=false}}
 const beforeUnload=(event:BeforeUnloadEvent)=>{if(dirty.value&&!allowLeave){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',beforeUnload);onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload));onBeforeRouteLeave(()=>allowLeave||saving.value||!dirty.value||window.confirm(t('promptops.editor.unsavedChanges')))
 return{form,loading,saving,error,issues,diagnostics,editMode,dirty,load,saveDraft,saveChanges,saveVersion,leave:async()=>{if(!dirty.value||window.confirm(t('promptops.editor.unsavedChanges'))){allowLeave=true;await router.push(editMode.value?`/prompts/${form.id}`:'/prompts')}}}}
