
export default { promptops: {
  brand:{subtitle:'企業 Prompt 管理與評測平台'},common:{comingSoon:'即將推出',comingSoonDescription:'此模組將在後續開發階段交付。',loading:'載入中…',loadError:'資料載入失敗。',initError:'PromptOps Studio 初始化失敗',retry:'重試',cancel:'取消',create:'建立',phase2:'Phase 2 提供'},
  nav:{overview:'概覽',promptManagement:'Prompt 管理',governance:'治理',system:'系統',dashboard:'儀表板',prompts:'Prompt 資產庫',playground:'調試台',invocations:'調用歷史',datasets:'測試資料集',evaluations:'評測',experiments:'實驗',approvals:'審批中心',models:'模型管理',analytics:'使用分析',settings:'設定',legacy:'舊版優化器'},roles:{aiProductManager:'AI 產品經理'},
  status:{draft:'草稿',testing:'測試中',pending_approval:'待審批',published:'已發布',archived:'已封存'},risk:{low:'低',medium:'中',high:'高'},
  dashboard:{title:'儀表板',description:'Prompt 資產健康度與治理概覽',viewLibrary:'查看 Prompt 資產庫',total:'Prompt 總數',published:'已發布',drafts:'草稿',pending:'待審批',averageScore:'平均評測分數',highRisk:'高風險 Prompt',statusDistribution:'Prompt 狀態分布',recentPrompts:'最近更新的 Prompt',noHighRisk:'暫無高風險 Prompt',recentActivity:'最近活動',activityHint:'此處活動由 Prompt 更新時間推導生成。',wasUpdated:'已更新'},
  library:{title:'Prompt 資產庫',description:'統一管理工作空間中的可重用 Prompt 資產',assets:'項資產',newPrompt:'新增 Prompt',descriptionField:'描述',emptyTitle:'未找到 Prompt',emptyDescription:'請調整或清除篩選條件。',archiveConfirm:'確認封存「{name}」？該資產仍會保留在歷史資料中。'},
  filters:{search:'搜尋名稱、描述或業務場景',allStatuses:'全部狀態',allCategories:'全部分類',allDepartments:'全部部門',allRisks:'全部風險等級',clear:'清除篩選'},
  table:{name:'名稱',scenario:'業務場景',category:'分類',department:'部門',owner:'負責人',version:'版本',model:'模型',status:'狀態',risk:'風險',score:'評測分數',updatedAt:'更新時間',actions:'操作'},actions:{view:'查看',edit:'編輯',duplicate:'複製',archive:'封存',copy:'副本'},
  detail:{title:'Prompt 詳情',back:'返回 Prompt 資產庫',backDashboard:'返回儀表板',notFound:'未找到 Prompt。',openPlayground:'在調試台中開啟',variables:'變數',required:'必填',optional:'選填',modelConfig:'模型設定'},
  editor:{createPrompt:'建立 Prompt',editPrompt:'編輯 Prompt',saveDraft:'儲存草稿',saveChanges:'儲存修改',saveNewVersion:'儲存為新版本',versionType:'版本類型',majorVersion:'主版本',minorVersion:'次版本',changeSummary:'變更摘要',changeReason:'變更原因',basicInformation:'基本資訊',promptContent:'Prompt 內容',variables:'變數',addVariable:'新增變數',noVariables:'使用雙大括號定義的變數會被自動識別。',variableDiagnostics:'變數診斷',invalidVariable:'變數名稱無效',unusedVariable:'未使用變數',removeVariable:'移除變數',modelConfig:'模型設定',outputConfig:'輸出設定',outputType:'輸出類型',expectedOutput:'預期輸出格式',unsavedChanges:'有未儲存的修改',promptNotFound:'未找到 Prompt',archivedCannotEdit:'已封存的 Prompt 無法編輯。',restorePrompt:'還原 Prompt'},
  version:{history:'版本歷史',detail:'版本詳情',currentVersion:'目前版本',versions:'個版本',restore:'還原為新版本',empty:'暫無版本。',notFound:'未找到版本。',backDetail:'返回 Prompt 詳情'},
  playground:{title:'使用現有 Prompt 優化工作區',description:'在專用 PromptOps 調試台完成前，繼續保留成熟的 Prompt Optimizer 工作區。',openLegacy:'開啟舊版優化器',capability1:'System 與 User Prompt 優化',capability2:'多模型測試與比較',capability3:'變數與多輪對話工作區'},
  datasets:{title:'資料集資產庫',description:'管理可重用的迴歸測試資料。',create:'建立資料集',edit:'編輯資料集',detail:'資料集詳情',name:'資料集名稱',descriptionField:'描述',active:'啟用',archived:'已封存',allStatuses:'全部狀態',testCases:'測試案例',addCase:'新增測試案例',editCase:'編輯測試案例',duplicateCase:'複製測試案例',deleteCase:'刪除測試案例',batchDelete:'批次刪除',selected:'已選擇 {count} 項',variables:'變數（JSON）',expectedOutput:'預期輸出',validationRules:'驗證規則',requiredKeywords:'必含關鍵字',forbiddenKeywords:'禁止關鍵字',exactMatch:'精確比對',outputType:'輸出類型',jsonFields:'JSON 欄位',jsonSchema:'JSON Schema',tags:'標籤',importDataset:'匯入資料集',exportDataset:'匯出資料集',selectFile:'選擇 JSON 檔案',importPreview:'匯入預覽',validCases:'有效案例',errors:'錯誤',warnings:'警告',caseIndex:'案例序號',jsonPath:'JSON 路徑',confirmImport:'確認匯入',importSuccess:'資料集匯入成功。',importFailed:'匯入失敗。',exportSuccess:'資料集已匯出。',empty:'暫無資料集。',noCases:'暫無測試案例。',noResults:'沒有符合篩選條件的結果。',notFound:'找不到資料集。',archivedReadonly:'已封存資料集為唯讀狀態。',restore:'還原資料集',archive:'封存資料集',archiveConfirm:'確認封存此資料集？',deleteConfirm:'確認刪除此測試案例？',batchDeleteConfirm:'確認刪除選中的測試案例？',fileTooLarge:'所選檔案過大。',invalidJson:'JSON 無效。',atomic:'匯入採用原子策略：任何錯誤都會阻止全部寫入。',runEvaluation:'執行評測',comingSoon:'即將推出',save:'儲存',close:'關閉',back:'返回資料集',search:'搜尋資料集',caseSearch:'搜尋測試案例',sort:'排序',status:'狀態',count:'共 {count} 個資料集',totalCases:'共 {count} 個測試案例',created:'建立時間',updated:'更新時間',actions:'操作',duplicate:'複製',clearFilters:'清除篩選',view:'查看',metadata:'編輯資訊'},evaluations:{configuration:'評估設定',dataset:'資料集',selectPrompt:'選擇提示詞',selectVersion:'選擇版本',selectModel:'選擇模型',noEnabledModels:'沒有已啟用模型',testCaseSelection:'測試案例選擇',allCases:'全部案例',selectedCases:'已選案例',filterByTag:'依標籤篩選',temperature:'溫度',maxTokens:'最大 Token',concurrency:'並行數',summary:'設定摘要',pricingUnavailable:'價格無法取得',start:'開始評估',running:'執行中',history:'評估歷史',historyDescription:'查看並重試批次評估執行。',search:'搜尋執行',allStatuses:'全部狀態',empty:'尚無評估執行。',run:'評估執行',prompt:'提示詞',model:'模型',progress:'進度',invocationSuccessRate:'呼叫成功率',validationPassRate:'驗證通過率',retryEntire:'重試全部',retryFailed:'重試失敗項目',retryCase:'重試此案例',delete:'刪除',deleteConfirm:'刪除此評估執行及其結果？',notFound:'找不到評估。',configurationSnapshot:'設定快照',cancel:'取消評估',cancelConfirm:'取消待執行案例？部分執行中請求可能無法中斷。',metrics:'指標',averageLatency:'平均延遲',totalTokens:'總 Token',totalCost:'總成本',averageScore:'平均分數',case:'測試案例',statusLabel:'狀態',deterministicValidation:'確定性驗證',latency:'延遲',tokens:'Token',output:'輸出',openInvocation:'開啟呼叫詳情',status:{queued:'排隊中',running:'執行中',completed:'已完成',completed_with_errors:'完成但有錯誤',failed:'失敗',cancelled:'已取消',pending:'待執行',succeeded:'呼叫成功',skipped:'已略過'}},settings:{about:'關於',openSource:'基於開源 Prompt Optimizer 專案建置，使用 AGPL-3.0 授權。'}
}} as const
