import{describe,expect,it,vi}from'vitest'
import{PromptInvocationService}from'../../../src/promptops/application/prompt-invocation-service'
import type{Prompt}from'../../../src/promptops/domain/prompt/types'
const prompt:Prompt={id:'p',workspaceId:'w',createdAt:'2026-01-01',updatedAt:'2026-01-01',name:'Test',description:'',businessScenario:'Support',category:'',department:'',owner:{id:'u',name:'User',role:'admin'},systemPrompt:'Hi {{name}}',userPrompt:'Reply',variables:[{id:'v',name:'name',displayName:'Name',type:'text',required:true}],outputType:'json',modelProvider:'mock',modelName:'mock-model',temperature:.2,maxTokens:20,status:'draft',riskLevel:'low',currentVersion:'V1.0'}
const setup=(fail=false)=>{const records=new Map<string,any>();const repository={create:vi.fn(async(v:any)=>{records.set(v.id,structuredClone(v));return structuredClone(v)}),update:vi.fn(async(v:any)=>{records.set(v.id,structuredClone(v));return structuredClone(v)}),getById:vi.fn(async(id:string)=>records.get(id)),list:vi.fn(),clear:vi.fn()};const llm={sendMessageStructured:vi.fn(async()=>{if(fail)throw new Error('API key sk-secret missing');return{content:'{"ok":true}',metadata:{tokens:7}}}),sendMessage:vi.fn(),sendMessageStream:vi.fn(),sendMessageStreamWithTools:vi.fn(),testConnection:vi.fn(),fetchModelList:vi.fn()};const service=new PromptInvocationService({getById:vi.fn(async()=>prompt)} as never,{getById:vi.fn()} as never,repository as never,llm as never);return{service,repository,llm,records}}
describe('PromptInvocationService',()=>{
 it('renders, calls, validates and persists success without mutating prompt',async()=>{const original=structuredClone(prompt),{service,repository}=setup();const result=await service.run({workspaceId:'w',promptId:'p',variableValues:{name:'Ada'},modelOverride:{streaming:false}});expect(result.output).toBe('{"ok":true}');expect(result.validation.valid).toBe(true);expect(result.invocation.tokenUsage.totalTokens).toBe(7);expect(repository.create).toHaveBeenCalled();expect(repository.update).toHaveBeenCalled();expect(prompt).toEqual(original)})
 it('blocks missing required variables before model invocation',async()=>{const{service,llm}=setup();await expect(service.run({workspaceId:'w',promptId:'p',variableValues:{}})).rejects.toThrow('Failed to render');expect(llm.sendMessageStructured).not.toHaveBeenCalled()})
 it('persists sanitized failed invocation',async()=>{const{service,records}=setup(true);await expect(service.run({workspaceId:'w',promptId:'p',variableValues:{name:'Ada'},modelOverride:{streaming:false}})).rejects.toThrow();const saved=[...records.values()][0];expect(saved.status).toBe('failed');expect(saved.errorMessage).not.toContain('sk-secret')})
})
