import'fake-indexeddb/auto'
import{afterEach,describe,expect,it}from'vitest'
import{DEFAULT_USER,DexiePromptRepository,DexiePromptVersionRepository,PromptEditorService,PromptOpsDatabase,type PromptDraftInput}from'../../../src/promptops'
let db:PromptOpsDatabase|undefined;afterEach(async()=>{if(db){await db.delete();db=undefined}})
const input=():PromptDraftInput=>({workspaceId:'w1',name:'Support Reply',description:'Safe reply',businessScenario:'Support',category:'Service',department:'CX',owner:DEFAULT_USER,systemPrompt:'Be concise',userPrompt:'Reply to {{message}}',variables:[],expectedOutputFormat:'',outputType:'text',modelProvider:'openai',modelName:'gpt-4.1-mini',temperature:.7,maxTokens:1000,status:'draft',riskLevel:'low'})
const setup=()=>{db=new PromptOpsDatabase(`editor-${crypto.randomUUID()}`);const prompts=new DexiePromptRepository(db),versions=new DexiePromptVersionRepository(db);return{prompts,versions,service:new PromptEditorService(db,prompts,versions)}}
describe('PromptEditorService',()=>{
 it('creates prompt and V1.0 atomically, then saves minor and major versions',async()=>{const{service,prompts,versions}=setup();let prompt=await service.create(input());expect(prompt.currentVersion).toBe('V1.0');expect(await versions.listByPromptId(prompt.id)).toHaveLength(1);await service.saveChanges({...prompt,description:'working copy'});expect(await versions.listByPromptId(prompt.id)).toHaveLength(1);await service.saveNewVersion({...prompt,description:'minor'},{changeSummary:'Minor'});prompt=(await prompts.getById(prompt.id))!;expect(prompt.currentVersion).toBe('V1.1');await service.saveNewVersion(prompt,{changeSummary:'Major',increment:'major'});expect((await prompts.getById(prompt.id))?.currentVersion).toBe('V2.0')})
 it('restores immutably and duplicates with a fresh V1.0 chain',async()=>{const{service,prompts,versions}=setup();let prompt=await service.create(input());const initial=(await versions.getLatest(prompt.id))!;await service.saveNewVersion({...prompt,name:'Changed'},{changeSummary:'Changed'});const restored=await service.restoreAsNew(prompt.id,initial.id,{changeSummary:'Restore'});expect(restored.versionNumber).toBe('V1.2');expect((await prompts.getById(prompt.id))?.name).toBe('Support Reply');expect((await versions.getById(initial.id))?.name).toBe('Support Reply');const copy=await service.duplicate(prompt.id);expect(copy.currentVersion).toBe('V1.0');expect(await versions.listByPromptId(copy.id)).toHaveLength(1)})
 it('enforces unique version numbers per prompt',async()=>{const{service,versions}=setup();const prompt=await service.create(input());const current=(await versions.getLatest(prompt.id))!;await expect(versions.create({...current,id:'duplicate'})).rejects.toThrow('already exists')})
 it('persists nested Proxy values from reactive UI forms as plain data',async()=>{const{service,prompts}=setup();const value=input();value.owner=new Proxy(value.owner,{});value.variables=[new Proxy({id:'variable-1',name:'message',displayName:'Message',type:'text',required:true}, {})];const prompt=await service.create(new Proxy(value,{}));expect((await prompts.getById(prompt.id))?.variables[0].name).toBe('message')})
})
